---
name: 'Build docker images'

on:
  pull_request:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: "slack"
            bundler_opts: >-
              --entrypoint /usr/bin/slack 
              --app-mounts /etc/resolv.conf 
              --app-mounts /dev 
              --app-mounts /home 
              --app-mounts /sys
              --app-mounts /tmp 
              --app-mounts /run
          - name: "balsa"
            bundler_opts: >-
              --entrypoint /usr/bin/balsa
              --app-mounts /etc/resolv.conf
              --app-mounts /home
              --app-mounts /sys
              --app-mounts /tmp
              --app-mounts /run
          - name: "clamtk"
            bundler_opts: >-
              --entrypoint /usr/bin/clamtk
              --app-mounts /etc/resolv.conf
              --app-mounts /home
              --app-mounts /sys
              --app-mounts /tmp
              --app-mounts /run
          - name: "gimp"
            bundler_opts: >-
              --entrypoint /usr/bin/gimp 
              --app-mounts /home 
              --app-mounts /sys 
              --app-mounts /tmp 
              --app-mounts /run
          - name: "libreoffice"
            bundler_opts: >-
              --entrypoint /usr/bin/libreoffice
              --app-mounts /home
              --app-mounts /sys
              --app-mounts /tmp
              --app-mounts /run
          - name: "lutris"
            bundler_opts: >-
              --entrypoint /usr/bin/lutris
              --app-mounts /dev
              --app-mounts /etc/resolv.conf
              --app-mounts /home
              --app-mounts /sys
              --app-mounts /tmp
              --app-mounts /run
          - name: "shortcut"
            bundler_opts: >-
              --entrypoint /usr/bin/shortcut
              --app-mounts /dev
              --app-mounts /home
              --app-mounts /sys
              --app-mounts /etc/resolv.conf
              --app-mounts /tmp
              --app-mounts /run
          - name: "snapd"
            bundler_opts: >-
              --entrypoint /usr/bin/snapd
              --app-mounts /dev
              --app-mounts /home
              --app-mounts /sys
              --app-mounts /etc/resolv.conf
              --app-mounts /tmp
              --app-mounts /run
          - name: "teams"
            bundler_opts: >-
              --entrypoint /usr/bin/teams
              --app-mounts /dev
              --app-mounts /home
              --app-mounts /sys
              --app-mounts /etc/resolv.conf
              --app-mounts /tmp
              --app-mounts /run
          - name: "zoom"
            bundler_opts: >-
              --entrypoint /usr/bin/zoom
              --app-mounts /dev
              --app-mounts /home
              --app-mounts /sys
              --app-mounts /tmp
              --app-mounts /etc/resolv.conf
              --app-mounts /run
          - name: "skype"
            bundler_opts: >-
              --entrypoint /usr/bin/skype
              --app-mounts /dev
              --app-mounts /home
              --app-mounts /sys
              --app-mounts /etc/resolv.conf
              --app-mounts /tmp
              --app-mounts /run
          - name: "inkscape"
            bundler_opts: >-
              --entrypoint /usr/bin/inkscape
              --app-mounts /dev
              --app-mounts /home
              --app-mounts /sys
              --app-mounts /tmp
              --app-mounts /run
          - name: "pidgin"
            bundler_opts: >-
              --entrypoint /usr/bin/pidgin
              --app-mounts /dev
              --app-mounts /home
              --app-mounts /sys
              --app-mounts /etc/resolv.conf 
              --app-mounts /tmp
              --app-mounts /run
          - name: "r-studio"
            bundler_opts: >-
              --entrypoint /usr/bin/r-studio
              --app-mounts /dev
              --app-mounts /home
              --app-mounts /sys
              --app-mounts /etc/resolv.conf
              --app-mounts /tmp
              --app-mounts /run
          - name: "google-chrome"
            bundler_opts: >-
              --entrypoint /usr/bin/google-chrome
              --app-mounts /dev
              --app-mounts /home
              --app-mounts /sys
              --app-mounts /etc/resolv.conf
              --app-mounts /tmp
              --app-mounts /run
          - name: "teamviewer"
            bundler_opts: >-
              --entrypoint /usr/bin/teamviewer
              --app-mounts /dev
              --app-mounts /etc/resolv.conf
              --app-mounts /home
              --app-mounts /sys
              --app-mounts /tmp
              --app-mounts /run
          - name: "vlc"
            bundler_opts: >-
              --entrypoint /usr/bin/vlc
              --app-mounts /dev
              --app-mounts /home
              --app-mounts /etc/resolv.conf
              --app-mounts /sys
              --app-mounts /tmp
              --app-mounts /run
          - name: "firefox"
            bundler_opts: >-
              --entrypoint /usr/bin/firefox
              --app-mounts /dev
              --app-mounts /home
              --app-mounts /sys
              --app-mounts /etc/resolv.conf
              --app-mounts /tmp
              --app-mounts /run
          - name: "thunderbird"
            bundler_opts: >-
              --entrypoint /usr/bin/thunderbird
              --app-mounts /dev
              --app-mounts /home
              --app-mounts /etc/resolv.conf
              --app-mounts /sys
              --app-mounts /tmp
              --app-mounts /run
          - name: "kodi"
            bundler_opts: >-
              --entrypoint /usr/bin/kodi
              --app-mounts /dev
              --app-mounts /home
              --app-mounts /sys
              --app-mounts /tmp
              --app-mounts /run
              --app-mounts /etc/resolv.conf
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
            go-version: '^1.17'
      - name: Build and install deps
        run: |
           wget https://github.com/mudler/poco/releases/download/v0.1.1/poco-v0.1.1-Linux-x86_64.tar.gz
           tar xvf poco-v0.1.1-Linux-x86_64.tar.gz
           sudo cp -rfv poco /usr/bin/
      - name: Build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./${{ matrix.name }}
          file: ./${{ matrix.name }}/Dockerfile
          tags: ${{ matrix.name }}:latest
      - name: Build bundle
        env:
          IMAGE: ${{ matrix.name }}:latest
          CGO_ENABLED: 0
        run: |
           mkdir build
           poco bundle \
            --local \
            --image $IMAGE \
            --app-name "${{ matrix.name }}" \
            --app-version "${GITHUB_SHA::8}" \
            --app-store '$HOME/.mos-app/${{ matrix.name }}' \
            --output build/${{ matrix.name }}-${GITHUB_SHA::8}-amd64 \
            ${{ matrix.bundler_opts }}
           echo "Generating checksum"
           sha256sum build/${{ matrix.name }}-${GITHUB_SHA::8}-amd64 > build/${{ matrix.name }}-${GITHUB_SHA::8}-amd64.sha256
      - name: Upload results
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.name }}-amd64
          path: build
          if-no-files-found: error
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/*
